import './menu.scss';
import './img/Football.png';
import './img/Football_hov.png';
import './img/Hockey.png';
import './img/Hockey_hov.png';
import './img/Basketball.png';
import './img/Basketball_hov.png'
import './img/Tennis.png';
import './img/Tennis_hov.png';
import './img/Volleyball.png';
import './img/Volleyball_hov.png';
import './img/Boxing.png';
import './img/Boxing_hov.png';
import './img/UFC.png';
import './img/UFC_hov.png';